# Generated by Django 4.2.5 on 2026-01-24 09:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
