# Generated by Django 6.0.1 on 2026-01-30 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_initial'),
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['date_held', 'start_time'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_date', 'start_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teaching.schedule'),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(default=9, help_text='Specific course type (lecture, lab, seminar, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teaching.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When this schedule patterns ends (defaults to semester end)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of ISO date strings to exclude (e.g. ['2026-03-15', '2026-04-20'])"),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_rule',
            field=models.TextField(default='', help_text='iCalendar RRULE format (e.g. FREQ=WEEKLY;BYDAY=MO,WE;INTERVAL=1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When this schedule pattern starts (defaults to semester start)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teaching.coursegroup'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.lecturer'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('schedule', 'date_held')},
        ),
    ]
