# Generated by Django 4.2.5 on 2026-01-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
        ('teaching', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('exam', 'Exam'), ('credit', 'Credit'), ('test', 'Test'), ('project', 'Project')], max_length=20)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='teaching.course')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_grades', to='users.lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
    ]
