# Generated by Django 6.0.1 on 2026-01-31 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_alter_class_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teaching.coursegroup'),
        ),
    ]
