# Generated by Django 6.0.1 on 2026-01-31 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_alter_course_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='teaching.course'),
        ),
    ]
