# Generated by Django 4.2.25 on 2025-12-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("workload", models.IntegerField(choices=[(40, "Full (40h)"), (20, "Half (20h)"), (30, "Three quarter (30h)")], default=40)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(choices=[("winter", "Winter"), ("summer", "Summer")], max_length=10)),
                ("academic_year", models.CharField(max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("faculty", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semesters", to="university.faculty")),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "unique_together": {("faculty", "academic_year", "type")},
            },
        ),
    ]
