# Generated by Django 4.2.25 on 2025-12-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_held", models.DateField()),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("weekly_hours", models.DecimalField(decimal_places=1, max_digits=4)),
                ("weeks_count", models.SmallIntegerField()),
                ("ects", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("course_group", models.CharField(blank=True, max_length=50, null=True)),
                ("course_type", models.CharField(choices=[("zal", "Credit"), ("zst", "Graded Credit"), ("egz", "Exam"), ("ekm", "Committee Exam")], max_length=10)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("weekday", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Course Group",
                "verbose_name_plural": "Course Groups",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("course_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teaching.coursegroup")),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
            },
        ),
    ]
