# Generated by Django 4.2.5 on 2025-12-19 02:38

import aws.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, storage=aws.s3.PrivateMediaStorage(), upload_to=''),
        ),
    ]
