/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(dashboard)': RouteRecordInfo<
      '/(dashboard)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(dashboard)/'
      | '/(dashboard)/employees/'
      | '/(dashboard)/employees/[id]'
      | '/(dashboard)/harmonogram'
      | '/(dashboard)/inbox'
      | '/(dashboard)/institutions/'
      | '/(dashboard)/institutions/[id]'
      | '/(dashboard)/settings/'
      | '/(dashboard)/subjects/'
      | '/(dashboard)/subjects/[id]'
    >,
    '/(dashboard)/': RouteRecordInfo<
      '/(dashboard)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/employees/': RouteRecordInfo<
      '/(dashboard)/employees/',
      '/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/employees/[id]': RouteRecordInfo<
      '/(dashboard)/employees/[id]',
      '/employees/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(dashboard)/harmonogram': RouteRecordInfo<
      '/(dashboard)/harmonogram',
      '/harmonogram',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/inbox': RouteRecordInfo<
      '/(dashboard)/inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/institutions/': RouteRecordInfo<
      '/(dashboard)/institutions/',
      '/institutions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/institutions/[id]': RouteRecordInfo<
      '/(dashboard)/institutions/[id]',
      '/institutions/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(dashboard)/settings/': RouteRecordInfo<
      '/(dashboard)/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/subjects/': RouteRecordInfo<
      '/(dashboard)/subjects/',
      '/subjects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/subjects/[id]': RouteRecordInfo<
      '/(dashboard)/subjects/[id]',
      '/subjects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(auth)/login': RouteRecordInfo<
      '/(auth)/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(help)/feedback': RouteRecordInfo<
      '/(help)/feedback',
      '/feedback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(help)/help': RouteRecordInfo<
      '/(help)/help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(dashboard).vue': {
      routes:
        | '/(dashboard)'
        | '/(dashboard)/'
        | '/(dashboard)/employees/'
        | '/(dashboard)/employees/[id]'
        | '/(dashboard)/harmonogram'
        | '/(dashboard)/inbox'
        | '/(dashboard)/institutions/'
        | '/(dashboard)/institutions/[id]'
        | '/(dashboard)/settings/'
        | '/(dashboard)/subjects/'
        | '/(dashboard)/subjects/[id]'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/index.vue': {
      routes:
        | '/(dashboard)/'
      views:
        | never
    }
    'src/pages/(dashboard)/employees/index.vue': {
      routes:
        | '/(dashboard)/employees/'
      views:
        | never
    }
    'src/pages/(dashboard)/employees/[id].vue': {
      routes:
        | '/(dashboard)/employees/[id]'
      views:
        | never
    }
    'src/pages/(dashboard)/harmonogram.vue': {
      routes:
        | '/(dashboard)/harmonogram'
      views:
        | never
    }
    'src/pages/(dashboard)/inbox.vue': {
      routes:
        | '/(dashboard)/inbox'
      views:
        | never
    }
    'src/pages/(dashboard)/institutions/index.vue': {
      routes:
        | '/(dashboard)/institutions/'
      views:
        | never
    }
    'src/pages/(dashboard)/institutions/[id].vue': {
      routes:
        | '/(dashboard)/institutions/[id]'
      views:
        | never
    }
    'src/pages/(dashboard)/settings/index.vue': {
      routes:
        | '/(dashboard)/settings/'
      views:
        | never
    }
    'src/pages/(dashboard)/subjects/index.vue': {
      routes:
        | '/(dashboard)/subjects/'
      views:
        | never
    }
    'src/pages/(dashboard)/subjects/[id].vue': {
      routes:
        | '/(dashboard)/subjects/[id]'
      views:
        | never
    }
    'src/pages/(auth)/login.vue': {
      routes:
        | '/(auth)/login'
      views:
        | never
    }
    'src/pages/(help)/feedback.vue': {
      routes:
        | '/(help)/feedback'
      views:
        | never
    }
    'src/pages/(help)/help.vue': {
      routes:
        | '/(help)/help'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
